### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by macrintr**
Co-authored-by: Barak Nehoran <bnehoran@users.noreply.github.com>
Co-authored-by: Sergiy Popovych <sergiy.popovich@gmail.com>
Co-authored-by: Davit Buniatyan <david.buniatyan@gmail.com>
Co-authored-by: Zhen Jia <jiazhen1987@gmail.com>
Co-authored-by: Nico Kemnitz <nkemnitz@princeton.edu>
Co-authored-by: Manuel Castro <macastro@princeton.edu>
Co-authored-by: Shang Mu <smu@princeton.edu>
Co-authored-by: Alexander Bae <jabae@princeton.edu>
Co-authored-by: Eric Mitchell eam6@seungworkstation1003.princeton.edu

### CODE REVIEW

**Review by manuel-castro — APPROVED** [review]
The Seamrippers would be a dope band name

**Review by davidbuniat — APPROVED** [review]
Looks good!

**Review by jabae — APPROVED** [review]

**Review by shangmu — APPROVED** [review]
Affirmed

**Review by bnehoran — APPROVED** [review]

**Review by nkemnitz — APPROVED** [review]

**Review by jiazhentim — APPROVED** [review]
Looks great

**Review by emitch — APPROVED** [review]
👍

**Pull request merged**
